interface Option {
    label: string;
    value: string;
    img: string;
}
export const data: Option[] = [
    { label: 'Poland', value: '+48', img: 'https://flagcdn.com/w80/pl.jpg' },
    { label: 'USA', value: '+1', img: 'https://flagcdn.com/w80/us.jpg' },
    { label: 'Algeria', value: '+213', img: 'https://flagcdn.com/w80/us.jpg' },
    { label: 'Andorra', value: '+376', img: 'https://flagcdn.com/w80/us.jpg' },
    { label: 'Angola', value: '+244', img: 'https://flagcdn.com/w80/ao.jpg' },
    { label: 'Argentina', value: '+54', img: 'https://flagcdn.com/w80/ar.jpg' },
    { label: 'Australia', value: '+61', img: 'https://flagcdn.com/w80/us.jpg' },
    { label: 'Austria', value: '+43', img: 'https://flagcdn.com/w80/us.jpg' },
    { label: 'Belgium', value: '+32', img: 'https://flagcdn.com/w80/us.jpg' },
    { label: 'Brazil', value: '+55', img: 'https://flagcdn.com/w80/us.jpg' },
    { label: 'Canada', value: '+1', img: 'https://flagcdn.com/w80/us.jpg' },
    { label: 'China', value: '+86', img: 'https://flagcdn.com/w80/us.jpg' },
    { label: 'Denmark', value: '+45', img: 'https://flagcdn.com/w80/us.jpg' },
    { label: 'Egypt', value: '+20', img: 'https://flagcdn.com/w80/us.jpg' },
    { label: 'France', value: '+33', img: 'https://flagcdn.com/w80/us.jpg' },
    { label: 'Germany', value: '+49', img: 'https://flagcdn.com/w80/us.jpg' },
    { label: 'Greece', value: '+30', img: 'https://flagcdn.com/w80/us.jpg' },
    { label: 'India', value: '+91', img: 'https://flagcdn.com/w80/us.jpg' },
    { label: 'Italy', value: '+39', img: 'https://flagcdn.com/w80/us.jpg' },
    { label: 'Japan', value: '+81', img: 'https://flagcdn.com/w80/us.jpg' },
    { label: 'Mexico', value: '+52', img: 'https://flagcdn.com/w80/us.jpg' },
    { label: 'Netherlands', value: '+31', img: 'https://flagcdn.com/w80/us.jpg' },
    { label: 'New Zealand', value: '+64', img: 'https://flagcdn.com/w80/us.jpg' },
    { label: 'Norway', value: '+47', img: 'https://flagcdn.com/w80/us.jpg' },
    { label: 'Portugal', value: '+351', img: 'https://flagcdn.com/w80/us.jpg' },
    { label: 'Russia', value: '+7', img: 'https://flagcdn.com/w80/us.jpg' },
    { label: 'South Africa', value: '+27', img: 'https://flagcdn.com/w80/us.jpg' },
    { label: 'South Korea', value: '+82', img: 'https://flagcdn.com/w80/us.jpg' },
    { label: 'Spain', value: '+34', img: 'https://flagcdn.com/w80/us.jpg' },
    { label: 'Sweden', value: '+46', img: 'https://flagcdn.com/w80/us.jpg' },
    { label: 'Switzerland', value: '+41', img: 'https://flagcdn.com/w80/us.jpg' },
    { label: 'Thailand', value: '+66', img: 'https://flagcdn.com/w80/us.jpg' },
    { label: 'Turkey', value: '+90', img: 'https://flagcdn.com/w80/us.jpg' },
    { label: 'Ukraine', value: '+380', img: 'https://flagcdn.com/w80/us.jpg' },
    { label: 'United Arab Emirates', value: '+971', img: 'https://flagcdn.com/w80/us.jpg' },
    { label: 'United Kingdom', value: '+44', img: 'https://flagcdn.com/w80/us.jpg' },
    { label: 'Vietnam', value: '+84', img: 'https://flagcdn.com/w80/us.jpg' },
    { label: 'Brazil', value: '+55', img: 'https://flagcdn.com/w80/us.jpg' },
    { label: 'Chile', value: '+56', img: 'https://flagcdn.com/w80/us.jpg' },
    { label: 'Colombia', value: '+57', img: 'https://flagcdn.com/w80/us.jpg' },
    { label: 'Peru', value: '+51', img: 'https://flagcdn.com/w80/us.jpg' },
];